name: Purge Branches
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # every day @ 10 AM UTC
jobs:
  purgeBranches:
    runs-on: ubuntu-latest
    steps:
      - name: Delete & Notify Branches
        uses: gita-vahdatinia/purge-branchn@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            days-to-notify: 0
            days-to-delete: 1
