# borrowed from https://github.com/marketplace/actions/remove-stale-branches
name: remove stale branches
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Everday at midnight

jobs:
  remove-stale-branches:
    name: Remove Stale Branches
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v1
        with:
          dry-run: true # Check out the console output before setting this to false
